### ISSUE TITLE
Not work littlefs in ESP32

### ISSUE THREAD

**Issue by first-leon** [xlyric/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn#13]
Hello. I flash ESP32 firmware. Download and flash https://ota.apper-solaire.org/firmware/littlefs-dimmer.bin.
![Screenshot_20230722_213544](https://github.com/xlyric/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn/assets/5301065/2ebb1fa3-a366-4d38-ae07-0db671521e20)

Reboot device, after i go http://IP and see:
![Screenshot_20230722_213655](https://github.com/xlyric/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn/assets/5301065/7cb56a07-4260-44ea-ba83-3ca9ea4a6012)

I flash last version fimware (commit c52445833cbea1cb377228e219172822a69911e0)

And i check it on esp8266 (standAlone). And it is work on esp8266

PS. I add ESP32-ETH (WT32-ETH01) profile. But i want check, how it work 
before create pull request (https://www.aliexpress.com/item/1005004432624600.html).

https://github.com/first-leon/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn/commit/0269ece6605c7691c5d14caa4e251fd9fafdcb9a

**Comment by xlyric** [comment]
Hi, 

with the ESP32, you must use this firmware for filesystem : https://ota.apper-solaire.org/firmware/spiffs-dimmer.bin 

it's not the same filesystem between ESP32 and ESP8266 . 

other things, I have lot of issues with ESP32, and everybody use ESP8266 ( it's work perfect and cheaper )

**Comment by first-leon** [comment]
Hello Cyril.
It doesn't work for me anyway.
For the test, i use ESP32_Devkitc_v4 (https://aliexpress.ru/item/1005005727909266.html) board and use the repository version c52445833cbea1cb377228e219172822a69911e0 (last commit in master).
I tried to upload a file https://ota.apper-solaire.org/firmware/spiffs-dimmer.bin but it doesn't work. I also tried using the build target "Upload Filesystem Image" over USB and it doesn't work either :(


"ESP8266 ( it's work perfect and cheaper )" - I agree with you. But I want to have a board that works not over wi-fi, but over ethernet. This board is also great: WT32-ETH01 (although more expensive).

**Comment by xlyric** [comment]
Ok, I know why it's not working, 
it's use the same 
        { "path": "firmware/partitions.bin", "offset": 32768 },
        { "path": "firmware/boot_app0.bin", "offset": 57344 },

between dimmer and router and I made a partition modification on router. 
I'm on holidays, you need to use VS code and compile all. 
I will make the modification when I'm back

**Comment by xlyric** [comment]
[spiffs.zip](https://github.com/xlyric/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn/files/12139009/spiffs.zip)
I think I have found, try this 
1 line is missing in plateformIO.ini 
board_build.filesystem = spiffs

**Comment by xlyric** [comment]
I can try, it's look good, 
-> https://ota.apper-solaire.org/ota.php 
-> ESP32 + Dimmer Robotdyn

**Comment by first-leon** [comment]
Great! I will check it tomorrow or the day after tomorrow on the ESP32_Devkitc_v4 board. Then I will check on the WT32-ETH01 board.

**Comment by xlyric** [comment]
ok, I will wait your feed back :D

**Comment by first-leon** [comment]
I checked ESP32_Devkitc_v . It works!
I will check WT32-ETH01.

**Comment by first-leon** [comment]
Everything is working now. I'm closing the question.

**Comment by xlyric** [comment]
Ok cool, i will check your commit when i m back

Le jeu. 3 août 2023 à 04:24, Vladimir Malyutin ***@***.***> a
écrit :
