### ISSUE TITLE
mode minuteur et température supérieure à consigne.

### ISSUE THREAD

**Issue by Dom1066** [xlyric/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn#19]
Ajout condition de température sinon le dimmer "yoyote" pendant 1 minute avec minuteur et température supérieure à consigne . le dimmer cherche a démarrer pendant 1 minute avec "contre-ordre" du à la température.(tout les 15 secondes?)
Il ne devrait pas chercher à démarrer du tout.
Solution ?
-minuteur.h
"142      if (heures == timeClient.getHours() && minutes == timeClient.getMinutes() &&  sysvar.celsius < temperature ) {"

**Comment by Dom1066** [comment]
après plusieurs essais, cela fonctionne.(plus de yoyo)

**Comment by xlyric** [comment]
ok, je vais faire la modification dans le code
