### ISSUE TITLE
Bug affichage

### ISSUE THREAD

**Issue by Dom1066** [xlyric/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn#23]
En haut de la page de configuration de la minuterie
l'heure affichée est "15:3" aulieu de "15:03"

**Comment by xlyric** [comment]
pris en compte, modif faite, en attente de 16h00

**Comment by Dom1066** [comment]
le même bug aussi sur le routeur...

**Comment by xlyric** [comment]
logique, la valeur minute est récupérée en json sur la page et directement affichée sur celle ci.
j'vais modifier heure et minute ainsi : 
var minute = data.minute < 10 ? "0" + data.minute : data.minute;

**Comment by Dom1066** [comment]
c'est mon gros défaut, je cherche les petits défauts...

Merci pou tout le travail...

**Comment by xlyric** [comment]
:D je préfère encore ça que les gros bugs à la noix
