### ISSUE TITLE
le ventilateur ne fonctionne pas en mode minuteur d'appoint.

### ISSUE THREAD

**Issue by Dom1066** [xlyric/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn#28]
Cette nuit le ventilateur n'a pas fonctionné en mode minuteur.
après un nouvel essais à l'instant (10h30), il a fonctionné 1 minute 30 puis s'est arrêté.(avec production insuffisante pour routée)
Nouvel essais avec puissance suffisante pour routée, il sest arrêté 1 minute 11 après de début de la programmation et le routage programmé qui continue.

**Comment by xlyric** [comment]
interessant, j'ai ma petite idée, je vais corriger

**Comment by xlyric** [comment]
tests : sans miniteur, mise d'un consigne, le ventillo reste en fonctionnement
puissance à 0 : mise en route du minuteur : RAS, le ventillo reste en fonctionnement.
relance d'une commande à 0, pendant la minuterie, le ventillateur fini par s'arreter. -> NOK
relance d'une commande à >0, pendant la minuterie, le ventillateur reste en fonctionnement -> RAS

du coup j'ai identifié le problème, je vais corriger ce soir

**Comment by xlyric** [comment]
corrigé
