### ISSUE TITLE
Remontée HA ventilo

### ISSUE THREAD

**Issue by Dom1066** [xlyric/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn#29]
En mode minuteur d'appoint, le ventilateur fonctionne correctement .
A la fin de la programmation/chauffe, le ventilateur s'arrête  mais Home assistant remonte qu'il continue à foncionner.

**Comment by xlyric** [comment]
ok, j'vais corriger. 
c'est étrange que ça l'ai pas remonté.

**Comment by Dom1066** [comment]
Mqtt explorer m'a remonté "0" en fin de programme au lieu de "false".

**Comment by xlyric** [comment]
en théorie, c'est la même chose. 
0 c'est false, par contre "false" c'est une chaine de caractères et du coup c'est plus false

**Comment by Dom1066** [comment]
state={"cooler" : "false"}
