### ISSUE TITLE
V20231023 les minuteurs d'appoints se déclenchent à l'heure GMT au lieu de prendre en compte le fuseau horaire

### ISSUE THREAD

**Issue by Samquad** [xlyric/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn#36]
le  déclenchement du minuteur dimmer ou relay2 programmé à 8H00 se déclenche en réalité à 9 heure.
J'en profite pour demander des infos sur la gestion des  minuteurs d'appoints:
si le minuteur est programmé sur la plage 8H00 - 11H00 comment est géré l'activation du minuteur?
sur les fronts ou sur la période programmée (ça peut avoir un impact sur une coupure de courant )
quand le minuteur est actif avec une consigne de 50°C réglée, la chauffe se coupe quand la consigne est atteinte mais à quelle température elle se réactive pour maintenir la température à 50°c?

Merci

**Comment by xlyric** [comment]
oui c'est normal comme il est passé en heure d'hiver depuis hier ( 25 octobre ), il est passé à GMT +1 
pour l'activation du minuteur, dans ton cas, il demarre à 8H jusqu'a soit avoir atteinds la température ou 11h 
dans le cas d'une coupure de courant dans cette période, il redémarrera éteins. 
le minuteur s'arretera dans tous les cas si la température est arrivé soit à la consigne, soit au réglage de température utilisé normalement ( au plus bas des 2 du coup ) pour des raisons de sécurités. 
https://wiki.apper-solaire.org/index.php?page=base-dimmer


en mode minuteur à température de sécurité , il n'y a pas de trigger et ça restera éteins jusqu'a la prochaine consigne du minuteur.  
pour le mode normal , le trigger est de -10% --> config.h  --> #define TRIGGER 10
