### ISSUE TITLE
heure page minuteur

### ISSUE THREAD

**Issue by Dom1066** [xlyric/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn#46]
Bonjour et bonne année.
Depuis quelques temps (passage à 2024 ?) l'heure sur la page minuteur est décalée de -1heure / à l'heure réelle et l'heure de la page index.
la programmation est alors décalée de 1heure.
(testé evec dernière version du git et c'est pareil)

**Comment by xlyric** [comment]
Salut, 

étrange, je regarderais. 
je suis sur la version du 23/11 et j'ai pas constaté le problème. ça apparait aussi sur l'heure de la page le décalage, ou c'est juste au déclenchement ?

**Comment by Dom1066** [comment]
ça apparait aussi sur l'heure de la page minuteur, la page index est juste.laprogrammation est décalée.

**Comment by Dom1066** [comment]
étrange !!! je viens de regarder par hasard (car je ne l'utilise pas) la page minuteur de mon PV routeur a aussi 1 heure de décalage !!!

**Comment by xlyric** [comment]
je viens de corriger sur le dimmer, je vais reporter la librairie sur le routeur
