### ISSUE TITLE
Dimmer bloqué 

### ISSUE THREAD

**Issue by elpigeondindo** [xlyric/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn#49]
Salut !

j'essai de corriger un bug récurrent sur mon dimmer.

Lorsque j'ai du surplus d'électricité, le routeur envoi bien l'info au dimmer mais le le dimmer est bloqué sur "dimmer at 100.00%".

L'interface web, le ping, les logs tout fonctionne normalement mais aucun envoi de puissance au SSR. J'ai verifié aussi si les infos remontées bien sur le server mqtt, et aucun souci je vois bien l'infos arrivée avec mqtt-explorer.

HTTP power at 100.00%
HTTP power at 100.00%
HTTP power at 100.00%
Dallas temp : 56.00
HTTP power at 100.00%
HTTP power at 100.00%
HTTP power at 100.00%
Dallas temp : 56.00
HTTP power at 100.00%
HTTP power at 100.00%
HTTP power at 100.00%
Dallas temp : 56.00

Sur le routeur et le dimmer je suis en version 20240225. Merci par avance.

**Comment by xlyric** [comment]
ça devrait être corrigé
