### ISSUE TITLE
embarquer les librairies JS pour utilisation sans internet

### ISSUE THREAD

**Issue by juliencarnot** [xlyric/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn#5]
Mon dimmer est connecté en wifi sur un réseau qui n'a pas accès à internet. Je dois donc me connecter à ce réseau pour accéder à son interface et modifier les paramètres (qui ont mystérieusement disparu), mais quand je n'ai donc pas accès aux différents CDN appelés pour les JS qui composent l'interface, qui s'affiche mal et n'enregistre pas les nouveaux paramètres (je les avais changé dans le projet et avant de compiler mais c'est fastidieux de tout redémonter et cabler).

Serait-il possible d'intégrer les librairies nécessaires dans le projet pour qu'elles soient en local sur le wemos?
Merci

**Comment by xlyric** [comment]
Bonjour Julien 

c'est ce que je faisais avant, mais le pb c'est que le wemos est un peu fablard pour répondre à toutes les requetes HTTP du coup j'ai du pour le mode non AP, d'exporter les librairies. 
2 options : 
soit que tu compiles l'ensemble et que tu changes les 4 pages HTML ( remarque en écrivant, je pourrais potentiellement te faire  le fichier. bin ) 
soit faire un mode pour ça... mais c'est plus long. 

je vais te faire un fichier à dispo en téléchargement pour que tu fasses une mise à jour par OTA
