### ISSUE TITLE
commandes MQTT

### ISSUE THREAD

**Issue by Dom1066** [xlyric/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn#52]
Bonjour,
les commandes MQTT à partir d'HA n'agissent plus sur le dimmer.

**Comment by xlyric** [comment]
ok, je vais regarder

**Comment by Dom1066** [comment]
dans l'historique d'éxecution des automatisations dans HA quand je fais "éxecuter" ,il y a
"Définir la valeur de <unknown entity>"
alors que dans la liste des entités dans HA tout est apparement bien défini.

**Comment by xlyric** [comment]
j'ai trouvé le problème d'enregistrement qu'il y avait, je teste de mon coté avant de mettre dans la branche main.
