### ISSUE TITLE
Perte remontées HA

### ISSUE THREAD

**Issue by Dom1066** [xlyric/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn#54]
En version 20240601 si je renomme le dimmer (hostname)  je n'ai plus les remontées MQTT dans HA.
Sans renommer , le ventilateur fonctionne mais dans HA il est  "à l'arrêt".

**Comment by xlyric** [comment]
je regarderais, mais si tu changes le nom, sous HA, techniquement ça risque aussi de changer le nom

**Comment by xlyric** [comment]
perte de connexion MQTT ? un autre chose, t'as regardé les logs MQTT pour voir ( si par exemple un Json mal formaté )
