### ISSUE TITLE
bouton HA "Reset alarme "

### ISSUE THREAD

**Issue by Dom1066** [xlyric/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn#55]
Bonjour,
quand j'appuie sur reset alarme dans HA,(la température est bien en dessous de la consigne) j'ai bien "Clear alarm temp" dans le log du dimmer, mais l'état reste sur "refroidissement" sur l'interface et le routage ne redémarre pas.

**Comment by xlyric** [comment]
ok, je vais regarder et  corriger.

**Comment by xlyric** [comment]
c'est corrigé
