### ISSUE TITLE
Un peu de doc sur la sauvegarde/restauration

### ISSUE THREAD

**Issue by brenard** [xlyric/PV-discharge-Dimmer-AC-Dimmer-KIT-Robotdyn#58]
Lors de ma dernière mise à jour, les logs du dimmer m'incitait à mettre à jour le FS, ce que j'ai fait. La page de mise à jour précise qu'il faut faire une sauvegarde de la configuration avant mise à jour (bonne idée !), mais comment faire :smile: J'ai cherché dans le wiki, mais je n'ai rien trouvé. À priori, il y a la solution de la sauvegarde via MQTT ou en téléchargeant le fichier JSON. Mais comment faire pour restaurer ? Ce serait pas mal d'avoir un peu de doc sur comment ça fonctionne dans le wiki :

- Sauvegarde via MQTT :
  - Qu'est-ce que contiennent ces sauvegardes ? J'ai l'impression qu'il n'y a pas tout, par exemple, les paramètres de connexion wifi et MQTT ou les minuteurs d'appoint.
  - Où est stockée la configuration ? à priori sur le serveur MQTT, mais est-ce que ces informations sont conservées dans le temps ou c'est perdu après un restart du service MQTT (tout du moins par défaut).

- Sauvegarde via JSON :
  - Qu'est-ce que contiennent ces sauvegardes ? (idem)
  - Comment restaurer la configuration à partir du fichier téléchargé précédemment ?

**Comment by xlyric** [comment]
pour la sauvegarde, c'est pourtant noté dans le wiki ici : 
https://wiki.apper-solaire.org/index.php?page=maj-dimmer

--> Cas d’une mise à jour du Filesystem 

pour le bouton de sauvegarde en MQTT, j'avoue ne pas l'avoir remis / testé depuis des lustres et je l'utilise pas. je note ça pour le mois prochain. 

la sauvegarde du json, ne prévois pas une restauration, c était aussi juste pour avoir les éléments sous les yeux lors de la recongfiguration. 

Dans tous les cas, la méthode indiqué dans le Wiki est limite la plus simple ( juste à sauver ses URL et les relancer )
